### ISSUE TITLE
Two Projectors Connected to One TripleHead2Go?

### ISSUE THREAD

**Issue by DanielArnett** [cr8tr/omnidome#12]
TripleHead2Gos work nicely with Omnidome when three projectors are connected to one TripleHead2Go. What about two projectors? I assume that currently Omnidome does not support using two projectors with a TripleHead, because it is  showing up as one very wide screen (I use 5 projectors with 2 TripleHead2Gos). 

Where is the TripleHead2Go support built in to Omnidome? I'm looking into adding support for my configuration.

**Comment by WilstonOreo** [comment]
there is a list of hard coded screen resolutions, in src/lib/proj/ScreenSetup.cpp

In line 143, the number of subscreens is calculated:
          if ((_screen->geometry().width() % _screenSize.width()) == 0)
          {
            return _screen->geometry().width() / _screenSize.width();
          }

So it tries to detect triple head by resolution.

**Comment by DanielArnett** [comment]
Strange, it looks like it should automatically detect a two-projector triple-head. I'll open it in a debugger and look at it tonight.

**Comment by DanielArnett** [comment]
I was using a non-standard resolution (1360x768 or something like that), that's why it didn't show up in Omnidome. I tried adding that resolution to the list in  `src/lib/proj/ScreenSetup.cpp`, but that led to a segmentation fault (which I couldn't debug since I'm not accustomed to debugging in vim yet). That said- I will try to switch to 1920x1080.

**Comment by WilstonOreo** [comment]
Hey, i finally merged the updated version with master. This version is part of a larger GL refactor.
It also fixes the QtCreator problem (qt integration with cmake is still shitty).
Qt 5.6 installation is now assumed to be in the home folder, otherwise you need to specify the absolute QT_PATH.

For building, you will need the cm8kr and omnicalib dependencies from now on, they need to be cloned into the directory of same level as omnidome itself.
The bootstrap.sh does that for you.

Will test the triple issue also.

Please test + Tell me when something doesn't work.

PS: I don't do debugging in vim, i usually do it from the command line via gdb on linux or lldb on mac.
lldb ./bin/Debug/omnidome.app/Contents/MacOS/omnidome
Console opens:
> r
... App crashes
> bt 
Print backtrace

**Comment by DanielArnett** [comment]
Awesome, thank you! I'll try it out and give feedback after I dig in.

**Comment by DanielArnett** [comment]
Okay, I'm now projecting properly through two projectors on one TripleHead2Go so I'll mark this as closed. The solution was to use standard projector resolutions, ensure that the TripleHead displays are all set to "Best for display" resolution in System Preferences -> Displays, and then to restart the computer.
